### ISSUE TITLE
对某些关键app失效

### ISSUE THREAD

**Issue by brijagstu7** [Lerist/FakeLocation#10]
在使用了模拟GPS信号、增强的反检测、root隐藏、基站模拟以及它们的组合之后，一些重要的软件仍然不能正常显示模拟的位置。

环境：OnePlus 7 Oxygen OS 10.0.1 gps和移动网络是打开状态，使用或者不使用境外VPN。

虚拟定位现在对于云闪付7.0.0、支付宝10.1.78都不能正常工作，软件会显示“无法定位”，“定位在所在地区不能使用”，需要说明的是我所模拟的位置都是中国大陆境内。

经测试，虚拟定位有效的软件主要是地图类应用。没有测试过钉钉。

**Comment by Lerist** [comment]
云闪付和支付宝都使用的基站定位, 在ROOT模式下开启基站模拟即可
