### ISSUE TITLE
1.3.1.9版本学习通无法签到

### ISSUE THREAD

**Issue by CN-Scars** [Lerist/FakeLocation#157]
用Fakeloacion 1.3.1.9版本进行位置模拟后学习通签到会获取不到位置信息，提示“未成功获取位置信息，请重新签到”

**Comment by coolxiao** [comment]
老哥怎么弄的

**Comment by CN-Scars** [comment]
> 老哥怎么弄的
这是因为模拟的位置仍然不够完美，联系作者之后得到的解决办法是：去实地采集一次位置，保存下来以后使用，可以解决此问题
