### ISSUE TITLE
会导致SELinux状态变成宽容模式

### ISSUE THREAD

**Issue by AmenLi** [Lerist/FakeLocation#163]
最近换了kernelsu做root，开机后打开fakelocation会必然导致kernelsu管理器里显示SELinux状态变成宽容模式。
请问这是FL的问题呢？还是kernelsu的问题？

FL 版本 1.3.2.2
![Screenshot_2023-07-10-17-45-13-973_me.weishu.kernelsu.jpg](https://github.com/Lerist/FakeLocation/assets/5909257/bca52ad5-16e5-4780-b375-b60102df3c5b)

之前在magisk下是什么样没注意过

**Comment by hldad** [comment]
软件要求，必须是宽容模式才能使用。

**Comment by c200154** [comment]
是宽容还用不了啊，一模拟就重启

**Comment by c200154** [comment]
如何确定能模拟，澎湃系统一点那个模拟就重启了
