### ISSUE TITLE
路线模拟里程会增加，步数不会自动增加

### ISSUE THREAD

**Issue by 1658745737** [Lerist/FakeLocation#175]

**Comment by 1658745737** [comment]
![Screenshot_2023-10-17-08-36-01-79](https://github.com/Lerist/FakeLocation/assets/148127621/6a9cdd00-dd0f-4d63-a4c6-7d666fc4b52a)
路线模拟会加里程数，不会加步数

**Comment by 1658745737** [comment]
是fl的权限不够吗？安卓十，系统里能给的都给了，应用权限没看到健身运动这一项

**Comment by JasonMQ0401** [comment]
那个速度里面有个模拟步数的，但是要root

**Comment by 1658745737** [comment]
已经root了能给的权限都给了

**Comment by 1658745737** [comment]
> 那个速度里面有个模拟步数的，但是要root

已经root过了，应该是没有要传感器权限

**Comment by JasonMQ0401** [comment]
我的步频太少，平台过不去，不知道咋办
