### ISSUE TITLE
钉钉打卡使用不了虚拟定位

### ISSUE THREAD

**Issue by kenxiong0113** [Lerist/FakeLocation#20]
各种问题，入坑需谨慎

**Comment by Lerist** [comment]
DD打卡需要做防检测操作, 防检测方法请参考[https://github.com/Lerist/FakeLocation/blob/master/FAQ/zh/FAQ.md#11%E9%81%BF%E5%85%8Ddd%E6%A3%80%E6%B5%8B](FAQ)

**Comment by didyqian** [comment]
> DD打卡需要做防检测操作, 防检测方法请参考[https://github.com/Lerist/FakeLocation/blob/master/FAQ/zh/FAQ.md#11%E9%81%BF%E5%85%8Ddd%E6%A3%80%E6%B5%8B](FAQ)

链接进去没内容？
