### ISSUE TITLE
位置模拟正常启动，路线模拟失败，已提交LOG和设置截图到作者邮箱

### ISSUE THREAD

**Issue by Kasum1zawaM1yu** [Lerist/FakeLocation#217]
使用系统版本：安卓14 | Realme UI5.0
使用手机型号：Realme GT 2 Pro
使用程序版本：1.3.5beta(1587)
使用面具版本：Kitsune Mask 26.4-kitsune-2(26400)
Xposed环境：Lsposed v1.9.2 (7058) **已经开启Xposed环境兼容依旧失败**
昨日前正常使用，今日突发程序模拟无效
**尝试了正式版1.3.2.2在安卓14无法使用**，点击模拟即重启，重启多次过后依旧无效，手机发烫严重（骁龙8Gen1）

此前也有过在beta版中，路线模拟界面等待加载（转圈）**过长时间**后，_切换至位置模拟环境界面再返回，却已经显示“正在运行”_，但是运行一定时间后，手机自动重启，模拟中断

**Comment by iqx6889** [comment]
哥，解决了吗，我也是路线模拟启动不了

**Comment by 0x04F5DA2** [comment]
我也是，路线模拟虚拟定位都不行

**Comment by Kasum1zawaM1yu** [comment]
> 哥，解决了吗，我也是路线模拟启动不了

暂时还没呢

**Comment by wyfang** [comment]
一样，小米14，开启后会卡住，只能长按电源。好奇软件都没更新为啥会突然不能用？系统也没更新。

**Comment by dinasourkris** [comment]
路线模拟没用啊，但是摇杆有用，研究半天毛都没研究出来

**Comment by dinasourkris** [comment]
急人
