### ISSUE TITLE
路线模拟用不了啊，一直转圈，位置模拟开了，直接无响应了

### ISSUE THREAD

**Issue by IKUN666346** [Lerist/FakeLocation#222]
逆天了呀

**Comment by guoyuheng111** [comment]
我也是

**Comment by IKUN666346** [comment]
现在好了，原因可能是在关虚拟机时没有停止路线模拟，最好是要把路线模拟关了再关虚拟机，这样基本就没有出过问题了

**Comment by guoyuheng111** [comment]
好的

在 2024-04-08 23:40:46，IKUN666346 ***@***.***> 写道：


现在好了，原因可能是在关虚拟机时没有停止路线模拟，最好是要把路线模拟关了再关虚拟机，这样基本就没有出过问题了
