### ISSUE TITLE
从4.13日晚开始路线模拟无法使用

### ISSUE THREAD

**Issue by SpectreAX** [Lerist/FakeLocation#237]

**Comment by guoyuheng111** [comment]
妈的为啥啊确实

**Comment by DianDianSun** [comment]
该怎么办呀

**Comment by SpectreAX** [comment]
> 妈的为啥啊确实


> 该怎么办呀

下载这个
https://www.123pan.com/s/CANijv-bGh43.html

**Comment by taojunnan** [comment]
用了新版本还是不行，你们呢

**Comment by SpectreAX** [comment]
> 用了新版本还是不行，你们呢

我用的 vmos 虚拟机，安卓7.1可以

**Comment by taojunnan** [comment]
谢谢，我把模拟器切到安卓7也可以了

> > 用了新版本还是不行，你们呢
> 
> 我用的 vmos 虚拟机，安卓7.1可以
