### ISSUE TITLE
mock has stopped 打开企业微信就提示这个，然后就停止模拟了

### ISSUE THREAD

**Issue by ShenKang4181** [Lerist/FakeLocation#258]
![8589a95f3f1434ba9ffd4317ea7acd4](https://github.com/Lerist/FakeLocation/assets/50401776/d8472fd3-f661-4ce5-b528-0210c9ab1af2)

**Comment by UsaMrs** [comment]
Regarding this issue, I am very interested in participating in the discussion. What version is your FakeLocation, what system is your mobile phone, and what version is your Wecom?

**Comment by ShenKang4181** [comment]
这个情况是最近才出现了几天，我一直这样使用可以正常打卡的，但是最近mock has stopped然后就不行了，我可以保证的是手机系统和企业微信我都没有升级，fake location本来是在用1.3.5beta之前的上一个版本，提示mock has stopped后就升级了一下，但是没有用
fake location 是1.3.5beta
企业微信是 4.0.0
手机是oppo find x7  ultra ,没有解锁刷机
![9fbeaa6adc68734cf5629293f935d90](https://github.com/Lerist/FakeLocation/assets/50401776/f3223a49-84b7-4d03-953f-cd6be5fab66b)
![8124a29ad26f206d0d3a1446e8ede61](https://github.com/Lerist/FakeLocation/assets/50401776/b3fd4c08-14aa-4e5a-a4d5-e69c3e8fda2f)
![ca799006c9776672782c81768177920](https://github.com/Lerist/FakeLocation/assets/50401776/9e66ce25-934d-42b7-bbec-5303d5fdb002)

**Comment by UsaMrs** [comment]
It is recommended to restore the version https://github.com/Lerist/FakeLocation/releases/tag/1.3.2.2, reset the fake location in the developer options and try again

**Comment by ShenKang4181** [comment]
> 建议[恢复版本 https://github.com/Lerist/FakeLocation/releases/tag/1.3.2.2](https://github.com/Lerist/FakeLocation/releases/tag/1.3.2.2)，在开发者选项中重置虚假位置，然后重试

i try it

**Comment by ShenKang4181** [comment]
没有mock has stopped了，明天早上我再试试[开心]

**Comment by ShenKang4181** [comment]
解决啦！[笔芯]
