### ISSUE TITLE
微信小程序无法定位

### ISSUE THREAD

**Issue by PakerYoung** [Lerist/FakeLocation#5]
锐行考勤，这个小程序无法定位，两台手机一个需要连接wifi能定位，一个直接无法定位，微信其他定位都正常，这应该是小程序问题？

**Comment by RussiaCoach** [comment]
你解决没有呀，救救弟弟呀

**Comment by YanAnHuaZai** [comment]
微信需要root才能定位

**Comment by RussiaCoach** [comment]
root了也不行我试过，不过我找了一个xp框架的软件解决了。

**Comment by YanAnHuaZai** [comment]
太极？

**Comment by RussiaCoach** [comment]
框架名字：lataclysm

**Comment by Lerist** [comment]
小程序用的是基站定位, 需要在ROOT模式下开启基站模拟, 并且需使用v1.2.0.5以上版本

**Comment by Kylewwb** [comment]
emmm,同问：root模式+基站定位 v1.2.0.8 小程序定位失败 微信本身定位是没有问题的

**Comment by Kylewwb** [comment]
emmm,同问：root模式+基站定位 v1.2.0.8 小程序定位失败 微信本身定位是没有问题的

**Comment by Kylewwb** [comment]
emmm,同问：root模式+基站定位 v1.2.0.8 小程序定位失败 微信本身定位是没有问题的

**Comment by Kylewwb** [comment]
> 框架名字：lataclysm

安装上了，咋用的呀

**Comment by RussiaCoach** [comment]
@Kylewwb 你就用这个把，这个我测试过小程序特别是锐行考勤要多刷几次才能成功。lataclysm这个要去踩点用手机拨打*#*#4636#*#*（安卓机）获得基站参数，麻烦的很。

**Comment by liuyihua-cn** [comment]
微信正常定位，小程序无法定位

**Comment by archieli** [comment]
微信正常定位，小程序无法定位

这个问题能解决吗？

**Comment by sunruicong** [comment]
这个能解决吗
