### ISSUE TITLE
反检测和root隐藏功能消失

### ISSUE THREAD

**Issue by Acpear** [Lerist/FakeLocation#74]
![Screenshot_20211022_162909.jpg](https://user-images.githubusercontent.com/84609589/138421063-be883a82-3608-456e-afa0-7003136471de.jpg)
如图，在联网之后两项功能消失，请问有没有找回方法

**Comment by wyfang** [comment]
现在开启了也没用了，app居然可以本地升级功能。反检测我手机用的xp框架到无所谓，但是现在单单开启定位效果没了。原本我也都是单开定位，是有效果的。
同求替代品。
